name: Scala CI con Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache de paquetes de Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Otorgar permisos de ejecución a gradlew
      run: chmod +x gradlew

    - name: Compilar con Gradle
      run: ./gradlew build -x test

    - name: Ejecutar pruebas
      run: ./gradlew test

    - name: Ejecutar run (salida consola)
      run: ./gradlew run

